"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()  # Carga las variables de entorno desde el archivo .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"
ENV_STATE = os.getenv("ENV_STATE", "local")

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "users",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Configuración de la base de datos MySQL utilizando variables de entorno
if ENV_STATE == "production":
    DATABASES = {}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "es-es"

TIME_ZONE = "America/Lima"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
AUTH_USER_MODEL = "users.User"


# Configuración de Django REST Framework para usar JWTAuthentication como método de autenticación predeterminado
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Configura la clase de throttling para limitar las solicitudes anónimas a 100 por día
    "DEFAULT_THROTTLE_CLASSES": {
        "rest_framework.throttling.AnnonRateThrottle",  # Limita las solicitudes anónimas a 100 por día
        "rest_framework.throttling.UserRateThrottle",  # Limita las solicitudes autenticadas a 1000 por día
    },
    # Configura las tasas de throttling para cada clase de throttling
    "DESFAULT_THROTTLE_RATES": {
        "anon": "50/minute",  # Limita las solicitudes anónimas a 50 por minuto
        "user": "100/minute",  # Limita las solicitudes autenticadas a 100 por minuto
        "login_attempt": "5/minute",  # Limita los intentos de inicio de sesión a 5 por minuto
    },
}


# Configuración de Simple JWT para manejar la autenticación basada en tokens JWT
SIMPLE_JWT = {
    # El token expira en 1 hora
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    # Tienes 1 día para pedir un nuevo token sin volver a loguearte
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    # Rotar tokens: cada vez que usas un refresh, te dan uno nuevo
    "ROTATE_REFRESH_TOKENS": True,
    # El token viejo va a la lista negra inmediatamente
    "BLACKLIST_AFTER_ROTATION": True,
    # El token se enviará en el encabezado de autorización como "Bearer <token>"
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}


# Configuración de drf-spectacular para la generación de documentación automática de la API
SPECTACULAR_SETTINGS = {
    "TITLE": "API de Finanzas Personales",
    "DESCRIPTION": "Documentación oficial de los endpoints del backend.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # --- CONFIGURACIÓN DEL SIDECAR ---
    "SWAGGER_UI_DIST": "SIDECAR",  # Le dice a Swagger que use los archivos locales
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}
